#!/bin/bash
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashland/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandgradadmis/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandadmissions/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandmba/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandiss/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlanded/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandcobe/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandcon/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandarts/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandfounders/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlanddevelop/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandstaf/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandadmin/sass; compass watch"
gnome-terminal -x bash -c "cd /var/www/d7.ashlandu/docroot/sites/all/themes/ashlandmahg/sass; compass watch"
