#!/bin/bash
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlanded/sass/ashlanded-ashland-default-mobile.scss' 
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashland/sass/ashland-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandgradadmis/sass/ashlandgradadmis-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandadmissions/sass/ashlandadmissions-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandmba/sass/ashlandmba-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandiss/sass/ashlandiss-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandcobe/sass/ashlandcobe-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandcon/sass/ashlandcon-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandarts/sass/ashlandarts-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandfounders/sass/ashlandfounders-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlanddevelop/sass/ashlanddevelop-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashlandmahg/sass/ashlandmahg-ashland-default-mobile.scss'
xdg-open '/var/www/d7.ashlandu/docroot/sites/all/themes/ashland/sass/all_sites_mobile/_ashland_all_sites_mobile.scss'
